### ISSUE TITLE
/latest/contracts.json

### ISSUE THREAD

**Issue by 0xngmi** [vesperfi/vesper-pools-v3#3]
can you add a file that points to the latest contracts.json? it would help us at defillama track all pools and keep that list updated

**Comment by rokso** [comment]
@0xngmi Let me review updates and push it out. Thanks

**Comment by 0xngmi** [comment]
could you also update the apis at https://github.com/DefiLlama/DefiLlama-Adapters/pull/2208/files#diff-fb6e9976e6dbf220ca391f8c4bac8fb25dc3755bc99d92d956c45c3754ef9e41R11

They seem to be outdated atm

**Comment by patidarmanoj10** [comment]
@0xngmi  

- I think we need not to read pool list from controller as we reading list from api.
- api seems correct and has all prod pools. I verified list of pools https://app.vesper.finance/ and pool address list in node test.js projects/vesper/index.js 
- There is still difference of TVL what node test.js projects/vesper/index.js  showing and what actually here https://app.vesper.finance/eth/stats.  Adapter calculating only 74M but actually its 95M in prod pools.

**Comment by g1nt0ki** [comment]
@patidarmanoj10 I just tried it locally as well and got 74M as tvl. the prod pools include 11M VSP tokens  in governance pool right? I am counting those under staking

**Comment by g1nt0ki** [comment]
when I add up the values in https://app.vesper.finance/eth/pools it matches the results from the terminal. the other 10M is not in any of these pools?

**Comment by patidarmanoj10** [comment]
oh. 11M is coming from https://api.vesper.finance/pools?stages=orbit. ( https://orbit.vesper.finance/). ~~I think we should not filter just prod but use all vesper pools. i.e https://api.vesper.finance/pools  . This include all pools prod, orbit, beta etc.~~

**Comment by patidarmanoj10** [comment]
Correction. 
We need to call two apis. 
 https://api.vesper.finance/pools?stages=orbit
and  
https://api.vesper.finance/pools?stages=prod

**Comment by g1nt0ki** [comment]
done: https://github.com/DefiLlama/DefiLlama-Adapters/pull/2224
